[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_USE_NPM = "true"
  NETLIFY_USE_PNPM = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@clerk/nextjs"]
  included_files = ["schema.sql"]
  # 增加内存限制
  memory = 3008
  # 增加超时时间
  timeout = "30s"

# 专门给生成视频的函数配置
[functions.gen-cover]
  included_files = ["schema.sql"]
  memory = 3008
  timeout = "900s"

# API routes 处理
[[edge_functions]]
  function = "gen-cover"
  pattern = "/api/gen-cover"