[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NETLIFY_USE_NPM = "true"
  NETLIFY_USE_PNPM = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 添加基本安全头
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[functions]
  included_files = ["public/**"]
  node_bundler = "esbuild"
  timeout = 30  # 设置为30秒