name = "stripe-webhook"
main = "webhook.ts"
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = "https://cwaaozrjfnktzvljkwdn.supabase.co"

# Secrets will be set using wrangler secret commands:
# - STRIPE_SECRET_KEY
# - STRIPE_WEBHOOK_SECRET
# - SUPABASE_SERVICE_ROLE_KEY