name = "clerk-webhook"
main = "workers/webhook.ts"
compatibility_date = "2024-01-01"

[vars]
SUPABASE_URL = "https://cwaaozrjfnktzvljkwdn.supabase.co"

[observability.logs]
enabled = true

# Secrets will be set using wrangler secret commands:
# - CLERK_WEBHOOK_SECRET
# - SUPABASE_SERVICE_ROLE_KEY