name = "aicover"
main = "src/worker.ts"
compatibility_date = "2024-01-28"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "aicover"
database_id = "" # 需要替换为实际的 database_id

[vars]
ENVIRONMENT = "production"

# 绑定 secrets（在部署时设置）
# wrangler secret put CLERK_SECRET_KEY
# wrangler secret put STRIPE_SECRET_KEY
# wrangler secret put STRIPE_WEBHOOK_SECRET
